# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ae31af1
_src_path: git+https://git.sr.ht/~nicoco/slidge-template
author: Nicoco
author_email: nicoco@nicoco.fr
author_website: https://nicoco.fr
dockerhub_username: nicocool84
legacy_lib: nio
legacy_lib_website: https://matrix-nio.readthedocs.io/
legacy_service: Matrix
legacy_service_website: https://matrix.org
module_name: matridge
project_name: matridge
python_version: '3.9'
srht_secret_c3p0: dc710d9d-8043-4e1d-9837-b35bfa02800a
srht_secret_docker: 173244e1-c233-43de-969f-65965c5487e1
srht_secret_pypi: 3ecea679-dec7-4ac0-8821-75d0f4fe0773
srht_username: nicoco
xeps:
-   note: Only groups are supported, even 1:1 chats show as groups.
    number: 45
    status: complete
-   note: For typing notifications.
    number: 85
    status: complete
-   note: There are no recipient-generated receipts (except read marks) in matrix,
        but slidge will emit delivery receipts when the matrix server acks a message.
    number: 184
    status: complete
-   number: 201
    status: complete
-   number: 245
    status: complete
-   note: null
    number: 319
    status: complete
-   note: null
    number: 308
    status: complete
-   note: For read markers.
    number: 333
    status: complete
-   note: For attachments.
    number: 363
    status: complete
-   note: Message received from XMPP will have their bodies parsed for Message Styling
        tags, plus "||spoiler||". Messages received from Matrix will not be parsed
        and converted.
    number: 393
    status: partial
-   note: Matrix's redacted events are mapped to that.
    number: 424
    status: complete
-   note: null
    number: 444
    status: complete
-   note: null
    number: 461
    status: complete
